### ISSUE TITLE
Unable to read secrets from store other than "root"

### ISSUE THREAD

**Issue by jbrmg** [mecodia/terraform-provider-pass#4]
Hi @toabi ,

I am not able to fetch secrets which are located in a store other than the default one as I get the response `entry is not in the password store`.

Example:

```
data "pass_password" "secret" {
  path = "mystore/mysecret"
}
```

I debugged the provider and found that the gopass library does not return these entries (e.g. when calling `st.List(context.Background())`. However, I found that updating the `github.com/gopasspw/gopass` dependency to `v1.15.1` solves the problem. 

Could you please update https://github.com/mecodia/terraform-provider-pass/pull/3 to the latest gopass dependency and merge it and perform a release? That would help me very much as I do not need to create yet another fork of the provider.

PS: Updating to `v1.14.11` as in the PR does not solve the issue, so the latest version is in-fact required.

Thanks

**Comment by toabi** [comment]
Hi, I just published [v3.1.0](https://github.com/mecodia/terraform-provider-pass/releases/tag/v3.1.0) and it also appeared on the [registry](https://registry.terraform.io/providers/mecodia/pass/3.1.0) :) hopefully with that all works as expected then. It's weird that the acceptance tests didn't catch this.
